import { pgTable, text, timestamp, integer, jsonb } from 'drizzle-orm/pg-core'

// One row per conversation. The id is a UUID generated by the client and stored
// in localStorage — no auth required for the demo. Replace with your own session
// strategy in production.
export const chatSessions = pgTable('chat_sessions', {
  id: text('id').primaryKey(),
  // Optional context data injected into the system prompt (user info, product state, etc.)
  context: jsonb('context').$type<Record<string, unknown>>(),
  // Set when AI escalates to Telegram; cleared when founder sends /done.
  escalatedAt: timestamp('escalated_at'),
  // The Telegram message_id we last sent — used to thread founder replies correctly.
  telegramMessageId: integer('telegram_message_id'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
})

export const chatTurns = pgTable('chat_turns', {
  id: text('id').primaryKey(),
  sessionId: text('session_id').notNull().references(() => chatSessions.id),
  role: text('role').notNull(), // 'user' | 'assistant'
  content: text('content').notNull(),
  // Set on Telegram-originated turns so replies stay threaded.
  telegramMessageId: integer('telegram_message_id'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
})
